### ISSUE TITLE
Fix problem with Minnesota Adjacency Matrix

### ISSUE THREAD

**Issue by jwbowers** [sbstusa/spilloverdesign#2]
Except for Minnesota, I think that the pair creation works.

**Comment by nahiggins** [comment]
Fantastic!  What's up with MN?

On Thu, Dec 31, 2015 at 5:59 PM, Jake Bowers notifications@github.com
wrote:

> Except for Minnesota, I think that the pair creation works.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sbstusa/spilloverdesign/issues/2.

## 

Nathaniel Higgins, Ph.D.
Fellow, White House Social & Behavioral Sciences Team
nathaniel.higgins@gsa.gov
(202) 302-9146

**Comment by jakesbst** [comment]
Not sure yet. Need to go through it more carefully.  I think county by
county.

On Thursday, December 31, 2015, nahiggins notifications@github.com wrote:

> Fantastic! What's up with MN?
> 
> On Thu, Dec 31, 2015 at 5:59 PM, Jake Bowers <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
> 
> > Except for Minnesota, I think that the pair creation works.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/sbstusa/spilloverdesign/issues/2.
> 
> ## 
> 
> Nathaniel Higgins, Ph.D.
> Fellow, White House Social & Behavioral Sciences Team
> nathaniel.higgins@gsa.gov
> <javascript:_e(%7B%7D,'cvml','nathaniel.higgins@gsa.gov');>
> (202) 302-9146
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sbstusa/spilloverdesign/issues/2#issuecomment-168267974
> .

## 

Jake Bowers

Social and Behavioral Sciences Team

Office of Evaluation Sciences | General Services Administration
jacob.bowers@gsa.gov amira.choueiki@gsa.gov | (202) 322-6714 | sbst.gov

**Comment by nahiggins** [comment]
OK, cool.

which file on github should i be looking at?  the markdown file?

On Thu, Dec 31, 2015 at 9:54 PM, Jake Bowers notifications@github.com
wrote:

> Not sure yet. Need to go through it more carefully. I think county by
> county.
> 
> On Thursday, December 31, 2015, nahiggins notifications@github.com
> wrote:
> 
> > Fantastic! What's up with MN?
> > 
> > On Thu, Dec 31, 2015 at 5:59 PM, Jake Bowers <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> > 
> > > Except for Minnesota, I think that the pair creation works.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/sbstusa/spilloverdesign/issues/2.
> > 
> > ## 
> > 
> > Nathaniel Higgins, Ph.D.
> > Fellow, White House Social & Behavioral Sciences Team
> > nathaniel.higgins@gsa.gov
> > <javascript:_e(%7B%7D,'cvml','nathaniel.higgins@gsa.gov');>
> > (202) 302-9146
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/sbstusa/spilloverdesign/issues/2#issuecomment-168267974
> > 
> > .
> 
> ## 
> 
> Jake Bowers
> 
> Social and Behavioral Sciences Team
> 
> Office of Evaluation Sciences | General Services Administration
> jacob.bowers@gsa.gov amira.choueiki@gsa.gov | (202) 322-6714 | sbst.gov
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sbstusa/spilloverdesign/issues/2#issuecomment-168278945
> .

## 

Nathaniel Higgins, Ph.D.
Fellow, White House Social & Behavioral Sciences Team
nathaniel.higgins@gsa.gov
(202) 302-9146

**Comment by jakesbst** [comment]
saturationDesign.Rmd should run . I just need figure out which MInnesota
county is causing problems.

On Thursday, December 31, 2015, nahiggins notifications@github.com wrote:

> OK, cool.
> 
> which file on github should i be looking at? the markdown file?
> 
> On Thu, Dec 31, 2015 at 9:54 PM, Jake Bowers <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
> 
> > Not sure yet. Need to go through it more carefully. I think county by
> > county.
> > 
> > On Thursday, December 31, 2015, nahiggins <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> > 
> > > Fantastic! What's up with MN?
> > > 
> > > On Thu, Dec 31, 2015 at 5:59 PM, Jake Bowers <notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>>
> > > wrote:
> > > 
> > > > Except for Minnesota, I think that the pair creation works.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/sbstusa/spilloverdesign/issues/2.
> > > 
> > > ## 
> > > 
> > > Nathaniel Higgins, Ph.D.
> > > Fellow, White House Social & Behavioral Sciences Team
> > > nathaniel.higgins@gsa.gov
> > > <javascript:_e(%7B%7D,'cvml','nathaniel.higgins@gsa.gov');>
> > > <javascript:_e(%7B%7D,'cvml','nathaniel.higgins@gsa.gov
> > > <javascript:_e(%7B%7D,'cvml','nathaniel.higgins@gsa.gov');>');>
> > > (202) 302-9146
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/sbstusa/spilloverdesign/issues/2#issuecomment-168267974
> > 
> > > .
> > 
> > ## 
> > 
> > Jake Bowers
> > 
> > Social and Behavioral Sciences Team
> > 
> > Office of Evaluation Sciences | General Services Administration
> > jacob.bowers@gsa.gov
> > <javascript:_e(%7B%7D,'cvml','jacob.bowers@gsa.gov');> <
> > amira.choueiki@gsa.gov
> > <javascript:_e(%7B%7D,'cvml','amira.choueiki@gsa.gov');>> | (202)
> > 322-6714 | sbst.gov
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/sbstusa/spilloverdesign/issues/2#issuecomment-168278945
> > 
> > .
> 
> ## 
> 
> Nathaniel Higgins, Ph.D.
> Fellow, White House Social & Behavioral Sciences Team
> nathaniel.higgins@gsa.gov
> <javascript:_e(%7B%7D,'cvml','nathaniel.higgins@gsa.gov');>
> (202) 302-9146
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sbstusa/spilloverdesign/issues/2#issuecomment-168280189
> .

## 

Jake Bowers

Social and Behavioral Sciences Team

Office of Evaluation Sciences | General Services Administration
jacob.bowers@gsa.gov amira.choueiki@gsa.gov | (202) 322-6714 | sbst.gov

**Comment by nahiggins** [comment]
THANKS!

On Fri, Jan 1, 2016 at 7:46 AM, Jake Bowers notifications@github.com
wrote:

> saturationDesign.Rmd should run . I just need figure out which MInnesota
> county is causing problems.
> 
> On Thursday, December 31, 2015, nahiggins notifications@github.com
> wrote:
> 
> > OK, cool.
> > 
> > which file on github should i be looking at? the markdown file?
> > 
> > On Thu, Dec 31, 2015 at 9:54 PM, Jake Bowers <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> > 
> > > Not sure yet. Need to go through it more carefully. I think county by
> > > county.
> > > 
> > > On Thursday, December 31, 2015, nahiggins <notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > > wrote:
> > > 
> > > > Fantastic! What's up with MN?
> > > > 
> > > > On Thu, Dec 31, 2015 at 5:59 PM, Jake Bowers <
> > > > notifications@github.com
> > > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> > > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>>
> > > > wrote:
> > > > 
> > > > > Except for Minnesota, I think that the pair creation works.
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > https://github.com/sbstusa/spilloverdesign/issues/2.
> > > > 
> > > > ## 
> > > > 
> > > > Nathaniel Higgins, Ph.D.
> > > > Fellow, White House Social & Behavioral Sciences Team
> > > > nathaniel.higgins@gsa.gov
> > > > <javascript:_e(%7B%7D,'cvml','nathaniel.higgins@gsa.gov');>
> > > > <javascript:_e(%7B%7D,'cvml','nathaniel.higgins@gsa.gov
> > > > <javascript:_e(%7B%7D,'cvml','nathaniel.higgins@gsa.gov');>');>
> > > > (202) 302-9146
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > 
> > https://github.com/sbstusa/spilloverdesign/issues/2#issuecomment-168267974
> > 
> > > > .
> > > 
> > > ## 
> > > 
> > > Jake Bowers
> > > 
> > > Social and Behavioral Sciences Team
> > > 
> > > Office of Evaluation Sciences | General Services Administration
> > > jacob.bowers@gsa.gov
> > > <javascript:_e(%7B%7D,'cvml','jacob.bowers@gsa.gov');> <
> > > amira.choueiki@gsa.gov
> > > <javascript:_e(%7B%7D,'cvml','amira.choueiki@gsa.gov');>> | (202)
> > > 322-6714 | sbst.gov
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/sbstusa/spilloverdesign/issues/2#issuecomment-168278945
> > 
> > > .
> > 
> > ## 
> > 
> > Nathaniel Higgins, Ph.D.
> > Fellow, White House Social & Behavioral Sciences Team
> > nathaniel.higgins@gsa.gov
> > <javascript:_e(%7B%7D,'cvml','nathaniel.higgins@gsa.gov');>
> > (202) 302-9146
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/sbstusa/spilloverdesign/issues/2#issuecomment-168280189
> > 
> > .
> 
> ## 
> 
> Jake Bowers
> 
> Social and Behavioral Sciences Team
> 
> Office of Evaluation Sciences | General Services Administration
> jacob.bowers@gsa.gov amira.choueiki@gsa.gov | (202) 322-6714 | sbst.gov
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sbstusa/spilloverdesign/issues/2#issuecomment-168304640
> .

## 

Nathaniel Higgins, Ph.D.
Fellow, White House Social & Behavioral Sciences Team
nathaniel.higgins@gsa.gov
(202) 302-9146

**Comment by jwbowers** [comment]
Found the problem. Implementing fix now in saturationDesign.Rmd. I'll close this issue with the next commit.

**Comment by jwbowers** [comment]
Fixed with commit 8c68a4969b3245cd95e14fe41bcbbaae7f0fc802
