### ISSUE TITLE
Clean up directory

### ISSUE THREAD

**Issue by nahiggins** [sbstusa/spilloverdesign#4]
...just need to clean up our work here...

**Comment by jakesbst** [comment]
Right. I'll look into
https://help.github.com/articles/remove-sensitive-data/

Jake Bowers

Social and Behavioral Sciences Team

Office of Evaluation Sciences | General Services Administration
jacob.bowers@gsa.gov amira.choueiki@gsa.gov | (202) 322-6714 | sbst.gov

**Comment by jwbowers** [comment]
done
